### ISSUE TITLE
Fatal error. Can not find vendor folder

### ISSUE THREAD

**Issue by presup** [leonstafford/wp2static-addon-cloudflare-workers#3]
Warning: require(/var/www/html/XXX/wp-content/plugins/wp2static-addon-cloudflare-workers/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/XXX/wp-content/plugins/wp2static-addon-cloudflare-workers/wp2static-addon-cloudflare-workers.php on line 22

Fatal error: require(): Failed opening required '/var/www/html/XXX/wp-content/plugins/wp2static-addon-cloudflare-workers/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/XXX/wp-content/plugins/wp2static-addon-cloudflare-workers/wp2static-addon-cloudflare-workers.php on line 22

**Comment by leonstafford** [comment]
Hi @presup, please ensure `composer install` has been run from within the directory, this will create the `vendor` dir

**Comment by presup** [comment]
Yes. I managed to figure that out. Successfully created the .zip and the plugin installed/activated without problems. However, I am unable to see the deploy option at the WP2Static option.

Thanks for the great work with the WP2Static plugin!

**Comment by leonstafford** [comment]
Hi @presup, sorry for the late reply. This should help explain how to deploy in V7: https://wp2static.com/docs/jobs/

Please let me know if any questions persist after reading that.

Cheers,

Leon

**Comment by cnvoicu** [comment]
Hey guys! I have had the same issue as @presup regarding not being able to see the WP2Static options and the issue is that on the Wordpress repo there's an older version of the plugin, to be more precise, 6.6.7. Downloading the latest version of W2PStatic fixes the issue.

Cheers,
Costin

**Comment by leonstafford** [comment]
Closing this old issue, but be aware that I've been doing some work on this repo and have a couple of pending issues left to prepare a new stable release of this Cloudflare add-on (these issues: https://github.com/leonstafford/wp2static-addon-cloudflare-workers/issues/12 https://github.com/leonstafford/wp2static-addon-cloudflare-workers/issues/11)
