### ISSUE TITLE
Tag for composer

### ISSUE THREAD

**Issue by thecodeassassin** [leonstafford/wp2static-addon-cloudflare-workers#5]
Hi all,

Would it be possible to create a tag or add this plugin to wpackagist.org? If I install this plugin via the github repository I'm unable to use installer-paths.

Thank you.

**Comment by leonstafford** [comment]
Sorry for not ever replying to this issue, @thecodeassassin! 

Published on Packagist and making a few other changes, then should be preparing a new stable release with proper tag/version.
